repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.4
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.3
    hooks:
    - id: python-safety-dependencies-check
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    - id: python-bandit-vulnerability-check