repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.4
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.3
    hooks:
    - id: python-safety-dependencies-check
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    - id: python-bandit-vulnerability-check
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
    - id: black
      language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.6.0'
    hooks:
      - id: autopep8
  - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: 'v0.3.3'
    hooks:
      - id: pep257
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
  - repo: https://github.com/PyCQA/pylint
    rev: 'v2.12.2'  # Use the sha / tag you want to point at
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      - id: dead